import Head from "next/head";
import { useState } from "react";
import { useWeatherData } from "./api/weathertwo";

export default function Home() {
  const [city, setCity] = useState("abuja");
  const { isLoading, data, error, refetch } = useWeatherData(city);

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  const temperature = data?.days?.[0]?.temp;
  const humidity = data?.days?.[0]?.humidity;
  const location = data?.resolvedAddress;

  const handleSearch = (e) => {
    e.preventDefault();
    refetch();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="phone">
        <div className="container">
          <div className="weather-side">
            <div className="weather-gradient"></div>
            <div className="date-container">
              <h2 className="date-dayname">Tuesday</h2>
              <span className="date-day">15 Jan 2019</span>
              <i className="location-icon" data-feather="map-pin"></i>
              <span className="location">{location}</span>
            </div>
            <div className="weather-container">
              <i className="weather-icon" data-feather="sun"></i>
              <h1 className="weather-temp">{temperature}</h1>
              <h3 className="weather-desc">Sunny</h3>
            </div>
          </div>
          <div className="info-side">
            <div className="today-info-container">
              <div className="today-info">
                <div className="precipitation">
                  {" "}
                  <span className="title">PRECIPITATION</span>
                  <span className="value">0 %</span>
                  <div className="clear"></div>
                </div>
                <div className="humidity">
                  {" "}
                  <span className="title">HUMIDITY</span>
                  <span className="value">{humidity}</span>
                  <div className="clear"></div>
                </div>
                <div className="wind">
                  {" "}
                  <span className="title">WIND</span>
                  <span className="value">0 km/h</span>
                  <div className="clear"></div>
                </div>
              </div>
            </div>
            <div className="week-container">
              <ul className="week-list">
                <li className="active">
                  <i className="day-icon" data-feather="sun"></i>
                  <span className="day-name">Tue</span>
                  <span className="day-temp">29°C</span>
                </li>
                <li>
                  <i className="day-icon" data-feather="cloud"></i>
                  <span className="day-name">Wed</span>
                  <span className="day-temp">21°C</span>
                </li>
                <li>
                  <i className="day-icon" data-feather="cloud-snow"></i>
                  <span className="day-name">Thu</span>
                  <span className="day-temp">08°C</span>
                </li>
                <li>
                  <i className="day-icon" data-feather="cloud-rain"></i>
                  <span className="day-name">Fry</span>
                  <span className="day-temp">19°C</span>
                </li>
                <div className="clear"></div>
              </ul>
            </div>
            <div className="location-container">
              <form onSubmit={handleSearch}>
                <input
                  type="text"
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                />
                <button className="location-button" type="submit">
                  {" "}
                  <i data-feather="map-pin"></i>
                  <span>Change location</span>
                </button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
